//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pipe_warning_info
    {
        public long id { get; set; }
        public int pipe_id { get; set; }
        public int area_id { get; set; }
        public int warning_level { get; set; }
        public float warning_value { get; set; }
        public System.DateTime warning_time { get; set; }
        public int warning_status { get; set; }
    }
}
